import{a as L,S as w,i as u}from"./assets/vendor-09d7c26e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p=s=>s.map(r=>`
    <li class="image-card">
        <a href="${r.largeImageURL}"
          ><img src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="img-descr">
          <li class="descr-el">Likes <span>${r.likes}</span></li>
          <li class="descr-el">Views <span>${r.views}</span></li>
          <li class="descr-el">Comments <span>${r.comments}</span></li>
          <li class="descr-el"> Downloads <span>${r.downloads}</span></li>
        </ul>
      </li>`).join(""),b="43829548-da808e6ec6af8b5210a63f940",M="https://pixabay.com/api/",g=async s=>await L.get(M,{params:{key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15}}),P=new w(".gallery-list a",{captionsData:"alt",captionDelay:250}),i=document.querySelector(".gallery-list"),S=document.querySelector(".search-form"),l=document.querySelector(".loader"),c=document.querySelector(".loadMoreBtn");async function O(s){s.preventDefault();try{const r=s.currentTarget.elements.userInput.value.trim();if(r==="")return i.innerHTML="",s.currentTarget.reset(),u.warning({message:"Type your query, please!",position:"center",timeout:3e3});i.innerHTML="",l.classList.remove("is-hidden");const o=await g(r);console.log("responseObj: ",o);const a=o.data.hits;console.log("imgArray: ",a);const e=o.data.total;console.log(e);let t=o.config.params.page;console.log("currentPage: ",t);const n=o.config.params.per_page;console.log("perPage: ",n);const d=Math.ceil(e/n);if(console.log("totalPages: ",d),a.length===0)return l.classList.add("is-hidden"),u.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"1.5",iconColor:"#fafafb"});l.classList.add("is-hidden");const m=await p(a);i.innerHTML=m,d>1&&(c.classList.remove("is-hidden"),c.addEventListener("click",()=>{try{t++;const y=g(r,t).data.hits;if(t<=d){const h=p(y);i.innerHTML+=h}else return c.classList.add("is-hidden"),u.error({position:"topRight",message:"We're sorry, there are no more pictures to load"})}catch{return new Error("Oops, something went wrong 😞")}})),s.target.reset(),P.refresh(),l.classList.add("is-hidden"),c.classList.add(".is-hidden")}catch{return new Error("Oops, something went wrong 😞")}}S.addEventListener("submit",O);
//# sourceMappingURL=commonHelpers.js.map
